# Generated by Django 5.2.6 on 2025-09-13 16:08

import django.db.models.deletion
import django_enumfield.db.fields
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('events_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('seat_mode', django_enumfield.db.fields.EnumField(default=1, enum=events.models.Events.SEAT_MODE)),
                ('status', django_enumfield.db.fields.EnumField(default=2, enum=events.models.Events.EVENT_STATUS)),
                ('sales_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sales_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('capacity_hint', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.events')),
            ],
            options={
                'db_table': 'ticket_type',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.venue'),
        ),
    ]
