# Generated by Django 5.2.6 on 2025-09-13 16:09

import analytics.models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFact',
            fields=[
                ('booking_fact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.BigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('action', django_enumfield.db.fields.EnumField(default=2, enum=analytics.models.BookingFact.ACTION)),
                ('tickets', models.PositiveIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_facts', to='events.events')),
            ],
            options={
                'db_table': 'booking_fact',
            },
        ),
        migrations.CreateModel(
            name='EventDailyRollup',
            fields=[
                ('event_daily_rollup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('bookings', models.PositiveIntegerField()),
                ('cancellations', models.PositiveIntegerField()),
                ('tickets_sold', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_daily_rollups', to='events.events')),
            ],
            options={
                'db_table': 'event_daily_rollup',
                'unique_together': {('event_id', 'day')},
            },
        ),
    ]
