# Generated by Django 5.2.6 on 2025-09-13 16:08

import accounts.models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('user_type', django_enumfield.db.fields.EnumField(default=1, enum=accounts.models.User.USER_TYPE)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserActiveSession',
            fields=[
                ('user_active_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_access_datetime', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'user_active_session',
            },
        ),
        migrations.CreateModel(
            name='UserSessionDump',
            fields=[
                ('user_session_dump_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=300)),
                ('login_datetime', models.DateTimeField()),
                ('logout_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_access_datetime', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_dumps', to='accounts.user')),
            ],
            options={
                'db_table': 'user_session_dump',
            },
        ),
    ]
