# Generated by Django 5.2.6 on 2025-09-15 17:43

import accounts.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=1, enum=accounts.models.User.USER_STATUS),
        ),
    ]
