# Generated by Django 5.2.6 on 2025-09-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhold',
            name='request_id',
            field=models.UUIDField(),
        ),
    ]
